#############################################################################
# Makefile for building: project1
# Generated by qmake (2.01a) (Qt 4.8.5) on: Fri Jun 16 11:45:12 2017
# Project:  project1.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.5/bin/qmake -o Makefile project1.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.5/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.5/include/QtCore -I/usr/local/Trolltech/Qt-4.8.5/include/QtGui -I/usr/local/Trolltech/Qt-4.8.5/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.5/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.5/lib -lQtGui -L/usr/local/Trolltech/Qt-4.8.5/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = address.cpp \
		addressview.cpp \
		bitslider.cpp \
		cacheview.cpp \
		main.cpp \
		resultsview.cpp \
		traceview.cpp \
		cachesimulator.cpp moc_addressview.cpp \
		moc_bitslider.cpp \
		moc_cacheview.cpp \
		moc_resultsview.cpp \
		moc_traceview.cpp
OBJECTS       = address.o \
		addressview.o \
		bitslider.o \
		cacheview.o \
		main.o \
		resultsview.o \
		traceview.o \
		cachesimulator.o \
		moc_addressview.o \
		moc_bitslider.o \
		moc_cacheview.o \
		moc_resultsview.o \
		moc_traceview.o
DIST          = /usr/local/Trolltech/Qt-4.8.5/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/include_source_dir.prf \
		project1.pro
QMAKE_TARGET  = project1
DESTDIR       = 
TARGET        = project1

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project1.pro  /usr/local/Trolltech/Qt-4.8.5/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.5/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.5/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.5/lib/libQtCore.prl
	$(QMAKE) -o Makefile project1.pro
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/shared.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.5/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.5/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile project1.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/project11.0.0 || $(MKDIR) .tmp/project11.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/project11.0.0/ && $(COPY_FILE) --parents address.h addressview.h bitslider.h cacheview.h resultsview.h traceview.h cachesimulator.h .tmp/project11.0.0/ && $(COPY_FILE) --parents address.cpp addressview.cpp bitslider.cpp cacheview.cpp main.cpp resultsview.cpp traceview.cpp cachesimulator.cpp .tmp/project11.0.0/ && (cd `dirname .tmp/project11.0.0` && $(TAR) project11.0.0.tar project11.0.0 && $(COMPRESS) project11.0.0.tar) && $(MOVE) `dirname .tmp/project11.0.0`/project11.0.0.tar.gz . && $(DEL_FILE) -r .tmp/project11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_addressview.cpp moc_bitslider.cpp moc_cacheview.cpp moc_resultsview.cpp moc_traceview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_addressview.cpp moc_bitslider.cpp moc_cacheview.cpp moc_resultsview.cpp moc_traceview.cpp
moc_addressview.cpp: addressview.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) addressview.h -o moc_addressview.cpp

moc_bitslider.cpp: bitslider.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) bitslider.h -o moc_bitslider.cpp

moc_cacheview.cpp: bitslider.h \
		cacheview.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) cacheview.h -o moc_cacheview.cpp

moc_resultsview.cpp: resultsview.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) resultsview.h -o moc_resultsview.cpp

moc_traceview.cpp: traceview.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) traceview.h -o moc_traceview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

address.o: address.cpp address.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o address.o address.cpp

addressview.o: addressview.cpp addressview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addressview.o addressview.cpp

bitslider.o: bitslider.cpp bitslider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bitslider.o bitslider.cpp

cacheview.o: cacheview.cpp cacheview.h \
		bitslider.h \
		addressview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cacheview.o cacheview.cpp

main.o: main.cpp bitslider.h \
		traceview.h \
		cacheview.h \
		resultsview.h \
		addressview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

resultsview.o: resultsview.cpp resultsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resultsview.o resultsview.cpp

traceview.o: traceview.cpp traceview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o traceview.o traceview.cpp

cachesimulator.o: cachesimulator.cpp cachesimulator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cachesimulator.o cachesimulator.cpp

moc_addressview.o: moc_addressview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addressview.o moc_addressview.cpp

moc_bitslider.o: moc_bitslider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bitslider.o moc_bitslider.cpp

moc_cacheview.o: moc_cacheview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cacheview.o moc_cacheview.cpp

moc_resultsview.o: moc_resultsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_resultsview.o moc_resultsview.cpp

moc_traceview.o: moc_traceview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_traceview.o moc_traceview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

